#!/usr/bin/env python3
"""Generate the Dart compatibility map for Arabic Presentation Forms-A/B.

The generated data comes exclusively from Python's bundled Unicode Character
Database. Characters without a Unicode decomposition are intentionally omitted
so decorative ligatures and symbols are preserved rather than guessed.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import unicodedata


PRESENTATION_FORM_RANGES = ((0xFB50, 0xFDFF), (0xFE70, 0xFEFF))
REQUIRED_UNICODE_VERSION = "15.0.0"
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "lib"
    / "quran_offline"
    / "arabic_presentation_forms.dart"
)


def _dart_string(value: str) -> str:
    return "".join(f"\\u{{{ord(char):X}}}" for char in value)


def render() -> str:
    entries: list[tuple[int, str]] = []
    for start, end in PRESENTATION_FORM_RANGES:
        for code_point in range(start, end + 1):
            char = chr(code_point)
            if not unicodedata.decomposition(char):
                continue
            decomposed = unicodedata.normalize("NFKD", char)
            if decomposed != char:
                entries.append((code_point, decomposed))

    lines = [
        "// GENERATED FILE - DO NOT EDIT.",
        "// Generated by tool/generate_arabic_forms.py from Python unicodedata",
        f"// Unicode Character Database {unicodedata.unidata_version}.",
        "// Source: https://www.unicode.org/ucd/",
        "library;",
        "",
        "/// Unicode compatibility decompositions for Arabic Presentation Forms-A/B.",
        "///",
        "/// Code points without an official decomposition are absent and therefore",
        "/// remain unchanged. This expands legacy shaped input to logical characters;",
        "/// it does not shape logical Arabic text for display.",
        "const Map<int, String> arabicPresentationFormDecompositions = <int, String>{",
    ]
    for code_point, decomposed in entries:
        key = f"0x{code_point:04X}"
        value = f"'{_dart_string(decomposed)}',"
        entry = f"  {key}: {value}"
        if len(entry) <= 100:
            lines.append(entry)
        else:
            lines.extend((f"  {key}:", f"      {value}"))
    lines.extend(
        [
            "};",
            "",
            "/// Expands Arabic Presentation Forms-A/B using Unicode compatibility data.",
            "String expandArabicPresentationForms(String input) {",
            "  if (input.isEmpty) return input;",
            "  StringBuffer? output;",
            "  var copiedUntil = 0;",
            "  for (final rune in input.runes) {",
            "    final replacement = arabicPresentationFormDecompositions[rune];",
            "    if (replacement == null) {",
            "      if (output != null) output.writeCharCode(rune);",
            "    } else {",
            "      output ??= StringBuffer(input.substring(0, copiedUntil));",
            "      output.write(replacement);",
            "    }",
            "    copiedUntil += rune > 0xFFFF ? 2 : 1;",
            "  }",
            "  return output?.toString() ?? input;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated Dart file differs from the checked-in file",
    )
    args = parser.parse_args()
    if unicodedata.unidata_version != REQUIRED_UNICODE_VERSION:
        print(
            "unsupported Unicode database: "
            f"{unicodedata.unidata_version}; expected {REQUIRED_UNICODE_VERSION} "
            "(use Python 3.12)",
            file=sys.stderr,
        )
        return 2
    content = render()
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated file: {args.output}", file=sys.stderr)
            return 1
        if current != content:
            print(f"generated file is stale: {args.output}", file=sys.stderr)
            return 1
        print(f"generated file is current: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(
        f"wrote {args.output} using Unicode {unicodedata.unidata_version}",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
